### ISSUE TITLE
Error: Cannot find module '../ConfigParser/ConfigParser'

### ISSUE THREAD

**Issue by jbagaresgaray** [OfficeDev/cordova-plugin-ms-outlook#3]
Subproject Path: CordovaLib

Subproject Path: cordova-plugin-ms-outlook/phs698647-CordovaOutlookServices

Failed to install 'cordova-plugin-ms-outlook':Error: Cannot find module '../ConfigParser/ConfigParser'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:77:12)
    at module.exports (/Applications/XAMPP/xamppfiles/htdocs/phs/plugins/cordova-plugin-ms-outlook/scripts/afterPluginInstall-android.js:8:28)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:187:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)

Error: Cannot find module '../ConfigParser/ConfigParser'

**Comment by erickbarbosa** [comment]
Any solution?

**Comment by Mdelaf** [comment]
I am having the same issue with a different plugin, did any of you manage to fix this?
